name: test composite action

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    pull_request_target:
      branches: [ main ]
    merge_group:
      branches: [ main ]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: run composite
              uses: ./.github/workflows/action.yml
              with:
                example_secret: ${{ secrets.example_secret }}